-- CachyOS Hyprland modulesuration

require("modules.animations")
require("modules.autostart")
require("modules.colors")
require("modules.decorations")
require("modules.variables")
require("modules.env")
require("modules.input")
require("modules.binds")
require("modules.misc")
require("modules.layout")
require("modules.monitors")
require("modules.windowrules")
require("modules.workspaces")